# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 12:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GephiVis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('file', models.FileField(max_length=500, upload_to='sna_assets/')),
                ('style', models.CharField(choices=[('Straight', 'straight'), ('Curvy', 'curvy')], default='Curvy', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LegendItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_description', models.CharField(max_length=50)),
                ('red', models.IntegerField(default=255, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)])),
                ('green', models.IntegerField(default=255, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)])),
                ('blue', models.IntegerField(default=255, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)])),
                ('visualisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sna.GephiVis')),
            ],
        ),
    ]
