# GN: code generated by AI Mode on Google web search (06/01/2026)
#from haystack.backends.elasticsearch_backend import ElasticsearchSearchBackend, ElasticsearchSearchEngine
from haystack.backends.elasticsearch7_backend import Elasticsearch7SearchBackend, Elasticsearch7SearchEngine

class CustomElasticsearchBackend(Elasticsearch7SearchBackend):
    def __init__(self, connection_alias, **connection_options):
        super().__init__(connection_alias, **connection_options)
        
        # Define the custom analyzer in index settings
        # This analyzer uses 'standard' tokenizer but NO stop-word filter
        self.DEFAULT_SETTINGS['settings']['analysis']['analyzer']['no_stopwords_analyzer'] = {
            "type": "custom",
            "tokenizer": "standard",
            "filter": ["lowercase"] 
        }

    def build_schema(self, fields):
        """
        Overrides the default schema builder to inject the custom analyzer
        into specific fields.
        """
        content_field_name, mapping = super().build_schema(fields)

        for field_name, field_class in fields.items():
            # Check for your specific field name (usually 'text')
            # and ensure it's an analyzed field (not a keyword/integer)
            if field_name == 'text':
                mapping[field_class.index_fieldname]['analyzer'] = 'no_stopwords_analyzer'
        
        return content_field_name, mapping

class CustomElasticsearchEngine(Elasticsearch7SearchEngine):
    backend = CustomElasticsearchBackend
