FROM docker.osgeo.org/geoserver:2.25.2
#COPY ./compose/geoserver/data/*.xml /opt/geoserver_data
#COPY ./compose/geoserver/data/layergroups/* /opt/geoserver_data/layergroups
#COPY ./compose/geoserver/data/workspaces/PoMS /opt/geoserver_data/workspaces