# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charter',
            name='helper_tickboxes',
            field=models.ManyToManyField(blank=True, help_text='Helper field used for the faceted search - see actionsmodels', to='pomsapp.DocTickboxes', verbose_name='normalization of tickboxes'),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='from_season',
            field=models.IntegerField(blank=True, choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Autumn'), (4, 'Winter')], help_text='season', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='from_weekday',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], help_text='weekday', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='to_day',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], help_text='day', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='to_month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='month', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='to_season',
            field=models.IntegerField(blank=True, choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Autumn'), (4, 'Winter')], help_text='season', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='to_weekday',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], help_text='weekday', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='facttransaction',
            name='helper_tickboxes',
            field=models.ManyToManyField(blank=True, help_text='Helper field used for the faceted search - see actionsmodels', to='pomsapp.TransTickboxes', verbose_name='normalization of tickboxes'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_types',
            field=models.ManyToManyField(blank=True, to='pomsapp.PlaceType'),
        ),
        migrations.AlterField(
            model_name='source',
            name='from_season',
            field=models.IntegerField(blank=True, choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Autumn'), (4, 'Winter')], help_text='season', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='source',
            name='from_weekday',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], help_text='weekday', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='source',
            name='to_day',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], help_text='day', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='source',
            name='to_month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='month', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='source',
            name='to_season',
            field=models.IntegerField(blank=True, choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Autumn'), (4, 'Winter')], help_text='season', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='source',
            name='to_weekday',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], help_text='weekday', null=True, verbose_name=''),
        ),
    ]
