# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomsapp', '0006_move_wagtail_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charter',
            options={'ordering': ['id'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
