# Generated by Django 2.1.5 on 2019-09-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pomsapp', '0008_auto_20181204_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoid',
            name='helper_places',
            field=models.ManyToManyField(blank=True, null=True, related_name='helper_factoids', to='pomsapp.Place', verbose_name='helper M2M table used to speed up searched in FB,                     from all factoids to all places (bypassing the possessions)'),
        )
    ]
