# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wordpress2wagtail', '0002_auto_20180217_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdlwordpressreference',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
