#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate
python /app/manage.py collectstatic --noinput
# python /app/manage.py update_index

if [[ $1 == *gunicorn ]]; then
    if [[ "$DJANGO_DEBUG" == "True" ]]; then
        exec "$@ --reload --reload-engine=poll --log-level=debug"
    else
        exec "$@"
    fi
else
    exec "$@"
fi
