# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pomsapp', '0002_auto_20180417_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seal',
            name='charter_field',
            field=models.ForeignKey(blank=True, db_column='charter_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='pomsapp.Charter', verbose_name='charter'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='matrix_field',
            field=models.ForeignKey(db_column='matrix_id', on_delete=django.db.models.deletion.CASCADE, to='pomsapp.Matrix', verbose_name='matrix'),
        ),
    ]
