# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('pomsapp_wagtail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='link_1_thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Link 1 Thumbnail'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_1_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link 1 Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_1_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link 1 URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_2_thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Link 2 Thumbnail'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_2_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link 2 Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_2_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link 2 URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_3_thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Link 3 Thumbnail'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_3_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link 3 Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_3_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link 3 URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_4_thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Link 4 Thumbnail'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_4_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link 4 Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_4_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link 4 URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
    ]
